### ISSUE TITLE
Old style tests fixture: TypeError: installProduct() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by nazrulworld** [collective/Products.LoginLockout#12]
When I am trying to run tests, got bellows errors.
```
Error in test /home/nazrul/www/python/CONTRIBUTIONS_FOLDER/Products.LoginLockout/Products/LoginLockout/../../README.rst
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 320, in run
    self.setUp()
  File "/home/nazrul/.cache/buildout/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/doctest/__init__.py", line 2206, in setUp
    self._dt_setUp(test)
  File "/home/nazrul/www/python/CONTRIBUTIONS_FOLDER/Products.LoginLockout/Products/LoginLockout/tests.py", line 71, in setUp
    installProduct('LoginLockout')
TypeError: installProduct() takes at least 2 arguments (1 given)

```

**Comment by djay** [comment]
@nazrulworld its fixed in https://github.com/collective/Products.LoginLockout/issues/11

**Comment by nazrulworld** [comment]
@djay sorry my bad didn't check get-tests-working branch :)
